### ISSUE TITLE
HA API not configured

### ISSUE THREAD

**Issue by jimz011** [home-assistant/home-assistant-iOS#320]

**Comment by robbiet480** [comment]
Fixed in build 51, build 50 was already pulled due to this.

**Comment by jimz011** [comment]
After installing build 50 the App throws this error. HA API not configured. Sensors get created, device tracker is created, but can not be updated manually by refreshing the app.

**Comment by jimz011** [comment]
Wow you are fast. I was still figuring out why the hell my issue got created before I even pressed submit :P.

**Comment by robbiet480** [comment]
Fixed via df75ea4174d3bc65b76d968e27baeca829fe0c92

**Comment by jimz011** [comment]
This problem persists in build 51, even after resetting integrations/app. Was it this build that should have fixed this?
