### ISSUE TITLE
Multiple events registered for entity-buttons on iOS 13 beta

### ISSUE THREAD

**Issue by mpeterson** [home-assistant/home-assistant-iOS#431]
**iOS version:** 13.0 (17A5565b)
**Device:** iPhone 8 Plus
**HA version:** 0.97.2

**Companion versions affected:** 2.0.0 (62) and 1.5.1

**Reproducibility rate:** Always

**Description:** 

Multiple events registered for `entity-button`s on iOS 13 beta. This means that when I press on a `entity-button` they will trigger toggles of status at least 2 times. In some cases I've seen it remain in an infinite loop and had to kill the app and restart HA to return to normality.

**Actual Behavior:**

Press on an `entity-button` and multiple events are sent to the server. Making their status toggle several times.

**Expected Behavior:**

Press on an `entity-button` and only one event is sent to the server (i.e. toggle the status once).

**Comment by mpeterson** [comment]
![Example](https://user-images.githubusercontent.com/11870/63499988-a790bb80-c4d1-11e9-96f3-897ef081e0e6.gif)

**Comment by SeanPM5** [comment]
Yup this has been an issue with all of the iOS 13 betas. The problem lies on Apple's end I believe, but it also seems unlikely that it's going to be fixed before the official release.

I just opened an issue here on the frontend repo if you'd like to follow it: https://github.com/home-assistant/home-assistant-polymer/issues/3510

**Comment by mpeterson** [comment]
Amazing @SeanPM5 ! Thanks a lot! I'll follow the issue you created!

**Comment by SeanPM5** [comment]
A fix for this should be included in Home Assistant 0.98 (see here: https://github.com/home-assistant/home-assistant-polymer/pull/3523) which is out now. 

Please give that a try whenever you get a chance and let me know if it resolves this double tap issue.

**Comment by mpeterson** [comment]
According to the change log this fix has not been included in 0.98 (confirmed by testing and still seeing the behavior).

I guess we’ll have to wait a bit more until the next release.

**Comment by mpeterson** [comment]
I stand corrected. It is not in the changelog, but it seems to be fixed (after clearing my cache).

 I could not confirm with an iPad as I haven't updated mine to the iOS13b.

**Comment by robbiet480** [comment]
Glad to hear it was resolved. Please reopen if needed.

**Comment by nenadmilano** [comment]
Problem with the double tap is still present for me on two iPad Air 2 with iPad OS 13.2.3 and Home Assistant App 2.0 (2019.1). Interesting thing is that i created a Safari PWA out of Home Assistant and there it does not show this behaviour.

**Comment by TomBrien** [comment]
I don't see this. What version of Home Assistant are you running?

**Comment by nenadmilano** [comment]
0.102.2 - my iPhone and iPad mini 4 does work properly, just the two ipad airs show this behaviour.

**Comment by TomBrien** [comment]
Ok something must have been missed in the frontend changes that is device specific. I suggest posting on @SeanPM5's issue over on the Polymer repo https://github.com/home-assistant/home-assistant-polymer/issues/3510

**Comment by nenadmilano** [comment]
thanks, did that!

**Comment by TomBrien** [comment]
Cheers. IS the problem present in standard Safari (not PWA'd version) on the iPad Airs?

**Comment by nenadmilano** [comment]
It works perfectly in Safari with or without a PWA. Only the new Home Assistant App shows this issuem the old one worked fine.

**Comment by TomBrien** [comment]
Ok based on that it strangely sounds like an app bug. Reopening here

**Comment by nenadmilano** [comment]
thanks, if i can support you in any way just tell me what you need.

**Comment by plw4** [comment]
I think I've found this same bug.  It only happens on my iPad Air (2019 version), but I get the issue in Safari as well as the app.  iOS 13.2.3.  iPhone 6S is fine. 

https://i.imgur.com/P4TI7qi.mp4

The first two presses are the entity-button at the bottom, the second two are the custom button-card, and the last is just flipping the switch at the top (which works as expected).  App version is 2.0.0 (69), HA is 0.103.0.

**Comment by williamstlr** [comment]
I'm experiencing this issue as well. Tested with the following devices

iPhone 7 (ios 13.3) - No issues
iPhone 8 (ios 13.3) - No issues
Desktop Firefox (v71.0) - No issues
iPad Air 2 (iPadOS 13.3) - Double tap issue

On the iPad it happens with both the app (v2.0.0 69) and in Safari
HA is version 0.103.4

Pulling logs from the app on the iPad I see the following

`
	2019-12-31 20:18:19.778 [Info] > Rotated file /private/var/mobile/Containers/Shared/AppGroup/50840E07-4A62-4A95-BC3B-7201469922CB/logs/log.txt to /private/var/mobile/Containers/Shared/AppGroup/50840E07-4A62-4A95-BC3B-7201469922CB/logs/log_2019-12-31_201819.txt
	2019-12-31 20:18:19.780 [Info] > Home Assistant Version: 2.0.0 Build: 69 PID: 187
	2019-12-31 20:18:19.780 [Info] > XCGLogger Version: 7.0.0 - Level: Debug
	2019-12-31 20:19:18.528 [Debug] [main] [SettingsViewController.swift:172] viewDidLoad() > Exporting logs as filename 2019-12-31T201918-0700_logs.zip
	2019-12-31 20:26:25.596 [Verbose] [main] [WebViewController.swift:648] handleHaptic(_:) > Handle haptic type light
	2019-12-31 20:26:25.723 [Verbose] [main] [WebViewController.swift:648] handleHaptic(_:) > Handle haptic type light
	2019-12-31 20:26:27.557 [Verbose] [main] [WebViewController.swift:648] handleHaptic(_:) > Handle haptic type light
	2019-12-31 20:26:27.658 [Verbose] [main] [WebViewController.swift:648] handleHaptic(_:) > Handle haptic type light
	2019-12-31 20:26:28.823 [Verbose] [main] [WebViewController.swift:648] handleHaptic(_:) > Handle haptic type light
	2019-12-31 20:26:29.000 [Verbose] [main] [WebViewController.swift:648] handleHaptic(_:) > Handle haptic type light
	2019-12-31 20:26:30.355 [Verbose] [main] [WebViewController.swift:648] handleHaptic(_:) > Handle haptic type light
	2019-12-31 20:26:30.478 [Verbose] [main] [WebViewController.swift:648] handleHaptic(_:) > Handle haptic type light
	2019-12-31 20:27:25.114 [Verbose] [main] [SettingsViewController.swift:165] viewDidLoad() > Logs directory is: file:///private/var/mobile/Containers/Shared/AppGroup/50840E07-4A62-4A95-BC3B-7201469922CB/logs/
	2019-12-31 20:27:25.115 [Debug] [main] [SettingsViewController.swift:172] viewDidLoad() > Exporting logs as filename 2019-12-31T202725-0700_logs.zip

`

**Comment by benaisn** [comment]
I got the same issue on iOS 13.3.1 (iPhone 11 Pro) and 13.3 (iPad).
I also see a lot of logs like that 

```
2020-02-10 18:06:34.187 [Verbose] [main] [WebViewController.swift:648] handleHaptic(_:) > Handle haptic type light
2020-02-10 18:06:34.979 [Verbose] [main] [WebViewController.swift:648] handleHaptic(_:) > Handle haptic type light
2020-02-10 18:06:35.147 [Verbose] [main] [WebViewController.swift:648] handleHaptic(_:) > Handle haptic type light
2020-02-10 18:06:35.809 [Verbose] [main] [WebViewController.swift:648] handleHaptic(_:) > Handle haptic type light
2020-02-10 18:06:35.941 [Verbose] [main] [WebViewController.swift:648] handleHaptic(_:) > Handle haptic type light
2020-02-10 18:06:36.577 [Verbose] [main] [WebViewController.swift:648] handleHaptic(_:) > Handle haptic type light
2020-02-10 18:06:36.703 [Verbose] [main] [WebViewController.swift:648] handleHaptic(_:) > Handle haptic type light
2020-02-10 18:06:37.484 [Verbose] [main] [WebViewController.swift:648] handleHaptic(_:) > Handle haptic type light
2020-02-10 18:06:37.602 [Verbose] [main] [WebViewController.swift:648] handleHaptic(_:) > Handle haptic type light
2020-02-10 18:06:38.447 [Verbose] [main] [WebViewController.swift:648] handleHaptic(_:) > Handle haptic type light
2020-02-10 18:06:38.553 [Verbose] [main] [WebViewController.swift:648] handleHaptic(_:) > Handle haptic type light
2020-02-10 18:06:39.279 [Verbose] [main] [WebViewController.swift:648] handleHaptic(_:) > Handle haptic type light
2020-02-10 18:06:46.905 [Verbose] [main] [WebViewController.swift:648] handleHaptic(_:) > Handle haptic type light
2020-02-10 18:06:47.040 [Verbose] [main] [WebViewController.swift:648] handleHaptic(_:) > Handle haptic type light
2020-02-10 18:06:48.684 [Verbose] [main] [WebViewController.swift:648] handleHaptic(_:) > Handle haptic type light
2020-02-10 18:06:48.889 [Verbose] [main] [WebViewController.swift:648] handleHaptic(_:) > Handle haptic type light
2020-02-10 18:06:50.426 [Verbose] [main] [WebViewController.swift:648] handleHaptic(_:) > Handle haptic type light
2020-02-10 18:06:50.598 [Verbose] [main] [WebViewController.swift:648] handleHaptic(_:) > Handle haptic type light
2020-02-10 18:06:51.107 [Verbose] [main] [WebViewController.swift:648] handleHaptic(_:) > Handle haptic type light
```

**Comment by robbiet480** [comment]
@benaisn what HA Core version? This should have been fixed in 0.105 via https://github.com/home-assistant/home-assistant-polymer/pull/4639 I believe.

**Comment by benaisn** [comment]
@robbiet480 I'm running 105.3 :(
It's really weird .. if I press the button like 1sec, it doesn't work (switching on then off, or off then on), And if I press like 2sec or 1.5 sec it works ... (I'm not talking about the long press, like 2/3 sec,  that would open the entity window)

![Screen Recording 2020-02-14 at 10 26 PM](https://user-images.githubusercontent.com/35267850/74568785-0f9ff600-4f79-11ea-92be-dbc4b10e9dd2.gif)

**Comment by williamstlr** [comment]
Seeing this exact behavior as well after updating to 0.105.3 on an ipad air 2 on ipasOS 13.3.1.

**Comment by TomBrien** [comment]
@benaisn and @williamstlr, do you see the same thing in safari?

**Comment by SeanPM5** [comment]
There was another fix for this merged two days ago: https://github.com/home-assistant/home-assistant-polymer/pull/4841 But hasn't made it into a release yet. 

Not sure if there will be an 0.105.4 release that will contain this fix, might have to wait until the 0.106 release (beta on Feb 19th and final on Feb 26th). But a fix is coming at least.

**Comment by williamstlr** [comment]
Just checked safari on my ipad and the issue is there as well. I’ll hang tight and wait for that fix to make it into a release then.

**Comment by benaisn** [comment]
thanks @SeanPM5 . let's wait for 0.106
Same issue on Safari.
