### ISSUE TITLE
Italian translation

### ISSUE THREAD

**Issue by namadori** [home-assistant/home-assistant-iOS#73]
Hi, ready to add Italian translation :-)

**Comment by robbiet480** [comment]
Done!

**Comment by namadori** [comment]
Still don’t see Italian in the available languages. Do I have to wait, or do something to enable it?

**Comment by robbiet480** [comment]
Did you already sign up? If so I need your email address to add you to the Italian translation

**Comment by robbiet480** [comment]
Added you to the Italian and Italian (Italy) translation
